### ISSUE TITLE
Nit: README typo in map function example

### ISSUE THREAD

**Issue by jimhotchkin-wf** [ympbyc/Carrot#34]
From the README:

**code 5** *defining a `map` function*

```lisp
(= (map (List a) (Fn a b) (List b))
  xs f
  (nil? xs nil
        (cons (f (car xs))
              (map (cdr xs) f))))
```
**code 6** *applying `map` function to a list*

```lisp
(map listX functionX) ;;A

(map (take integers 5) (+ 2)) ;;B
```
The following section refers to a `lst` variable which is not defined in **code 5**.  Corrected section is ~`struck-through`~ below:

> In the expression A, the `map` function defined in **code 5** is applied to two arguments; listX and functionX assuming they are defined elsewhere.
> This fills the parameter slots of the `map` function meaning that `listX` gets bound to ~`lst`~ `xs` and `functionX` gets bound to `f`. The expression inside `map` is then evaluated using both `listX` and `functionX`. Eventually the evaluation completes; producing a value(in this case a new list).

**Comment by ympbyc** [comment]
Thanks!
